services:
  backend:
    mem_limit: 32G
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GEIST_DATABASE_PROVIDER=sqlite
      - SQLITE_DATABASE_PATH=data/geist.sqlite3
      - DEBUG=${DEBUG:-}
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN:-}
    env_file:
      - path: .env
        required: false
    volumes:
      - ./:/opt/geist
    ports:
      - "5001:5001"
      - "5678:5678"
    networks:
      test_net:
        aliases:
          - geistlocal.com
          - backend

  frontend:
    build:
      context: .
      dockerfile: client/geist/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/geist:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_HOST=backend
      - REACT_APP_BACKEND_PORT=5001
    depends_on:
      - backend
    networks:
      - test_net

networks:
  test_net:
