version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URI=postgresql://geist:geist@db:5432/db
      - DEBUG=${DEBUG:-}
    depends_on:
      - db
    env_file:
      - ".env"
    volumes:
      - ./:/opt/geist
    ports:
      - "5001:5000"
      - "5678:5678"
    networks:
      test_net:
        aliases:
          - geistlocal.com

  db:
    image: postgres:14.9
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=geist
      - POSTGRES_PASSWORD=geist
      - POSTGRES_DB=db
    networks:
      - test_net

  frontend:
    build:
      context: .
      dockerfile: client/geist/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/geist:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - test_net

networks:
  test_net:

volumes:
  postgres_data: