services:
  frontend:
    build:
      context: .
      dockerfile: client/geist/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/geist:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_HOST=host.docker.internal
      - REACT_APP_BACKEND_PORT=5001
    networks:
      - test_net

networks:
  test_net: