version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - DATABASE_URI=postgresql://geist:geist@db:5432/db
      - DEBUG=${DEBUG:-}
    depends_on:
      - db
    env_file:
      - ".env"
    volumes:
      - ./:/opt/geist
    ports:
      - "5001:5000"
      - "5678:5678"
    networks:
      test_net:
        aliases:
          - geistlocal.com

  db:
    image: postgres:14.9
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=geist
      - POSTGRES_PASSWORD=geist
      - POSTGRES_DB=db
    networks:
      - test_net

  frontend:
    build:
      context: ./client  # Adjust this path to where your frontend code is located
      dockerfile: Dockerfile  # Create a Dockerfile for your frontend if you haven't already
    ports:
      - "3000:3000"  # Assuming your React app runs on port 3000
    volumes:
      - ./frontend:/app  # For hot-reloading during development
      - /app/node_modules  # To prevent overwriting node_modules with the host's
    environment:
      - NODE_ENV=development  # Set to production for production builds
    depends_on:
      - backend
    networks:
      - test_net

networks:
  test_net:

volumes:
  postgres_data: