version: 2.0

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    environment:
    - DATABASE_URI=postgresql://geist:geist@db:5432/db
    - DEBUG=$(DEBUG:-}
    depends_on:
      - db
    env_file:
      - ".env"
    volumes:
      - ./:/opt/geist
    ports:
      - "5000:5000"
      - "5678:5678"
    networks:
      test_net:
        aliases:
          - geistlocal.com
db:
  image: postgres:14.9
  restart: always
  ports:
    - "5432:5432"
  volumes:
    - postgres_data:/var/lib/postgresql/data
  environment:
    - POSTGRES_USER=geist
    - POSTGRES_PASSWORD=geist
    - POSTGRES_DB=db


