# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# This file will be regenerated by grpcio-tools from proto/inference.proto
# For now, we define the message classes manually.

from dataclasses import dataclass, field
from typing import List, Dict, Optional


@dataclass
class Message:
    role: str = ""
    content: str = ""
    name: str = ""


@dataclass
class GenerationConfig:
    max_tokens: int = 256
    temperature: float = 0.7
    top_p: float = 1.0
    frequency_penalty: float = 0.0
    presence_penalty: float = 0.0
    stop_sequences: List[str] = field(default_factory=list)
    top_k: int = 0
    repetition_penalty: float = 1.0


@dataclass
class CompletionRequest:
    model_id: str = ""
    system_prompt: str = ""
    user_prompt: str = ""
    config: Optional[GenerationConfig] = None
    chat_history: List[Message] = field(default_factory=list)


@dataclass
class UsageStats:
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0


@dataclass
class CompletionResponse:
    id: str = ""
    content: str = ""
    finish_reason: str = ""
    usage: Optional[UsageStats] = None
    model_id: str = ""
    created: int = 0


@dataclass
class TokenChunk:
    token: str = ""
    is_final: bool = False
    finish_reason: str = ""
    index: int = 0
    logprob: float = 0.0


@dataclass
class LoadModelRequest:
    model_id: str = ""
    runner_type: str = ""
    device_config: Dict[str, str] = field(default_factory=dict)
    quantization: str = ""


@dataclass
class LoadModelResponse:
    success: bool = False
    message: str = ""
    load_time_ms: int = 0
    memory_usage_bytes: int = 0


@dataclass
class UnloadModelRequest:
    model_id: str = ""


@dataclass
class UnloadModelResponse:
    success: bool = False
    message: str = ""


@dataclass
class ListModelsRequest:
    include_unloaded: bool = False


@dataclass
class ModelInfo:
    id: str = ""
    name: str = ""
    loaded: bool = False
    context_window: int = 0
    supports_streaming: bool = True
    family: str = ""
    parameter_count: int = 0
    quantization: str = ""


@dataclass
class ListModelsResponse:
    models: List[ModelInfo] = field(default_factory=list)


@dataclass
class GetModelInfoRequest:
    model_id: str = ""


@dataclass
class GetModelInfoResponse:
    model: Optional[ModelInfo] = None
    exists: bool = False


@dataclass
class HealthRequest:
    pass


@dataclass
class HealthResponse:
    status: str = ""
    version: str = ""
    loaded_models: int = 0
    uptime_seconds: int = 0
    memory_usage_bytes: int = 0
