"""create workflow tables

Revision ID: 0f40002d3d1f
Revises: adafc1380eb9
Create Date: 2025-05-18 04:13:16.513391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f40002d3d1f'
down_revision: Union[str, None] = 'adafc1380eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
        sa.Column('workflow_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['geist_user.user_id'], ),
        sa.PrimaryKeyConstraint('workflow_id')
    )
    
    op.create_table('workflow_step',
        sa.Column('step_id', sa.Integer(), nullable=False),
        sa.Column('workflow_id', sa.Integer(), nullable=True),
        sa.Column('step_name', sa.String(), nullable=True),
        sa.Column('step_description', sa.String(), nullable=True),
        sa.Column('step_status', sa.String(), nullable=True),
        sa.Column('display_x', sa.Integer(), nullable=True),
        sa.Column('display_y', sa.Integer(), nullable=True),
        sa.Column('command_str', sa.String(), nullable=True),
        sa.Column('step_type', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['workflow_id'], ['workflow.workflow_id'], ),
        sa.PrimaryKeyConstraint('step_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_step')
    op.drop_table('workflow')
    # ### end Alembic commands ###
