"""Add LangGraph checkpoint fields

Revision ID: a1b2c3d4e5f6
Revises: f1a2b3c4d5e6
Create Date: 2026-01-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add LangGraph checkpoint fields to agent table
    op.add_column('agent', sa.Column('checkpoint_data', sa.String(), nullable=True))
    op.add_column('agent', sa.Column('checkpoint_metadata', sa.String(), nullable=True))
    op.add_column('agent', sa.Column('pending_writes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove LangGraph checkpoint fields from agent table
    op.drop_column('agent', 'pending_writes')
    op.drop_column('agent', 'checkpoint_metadata')
    op.drop_column('agent', 'checkpoint_data')
    # ### end Alembic commands ###
