"""Initial migration

Revision ID: d7f88cab37e0
Revises: 
Create Date: 2024-07-20 23:22:38.111094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f88cab37e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('agent_identifier', sa.String(), nullable=True),
    sa.Column('process_id', sa.String(), nullable=True),
    sa.Column('world_context', sa.String(), nullable=True),
    sa.Column('task_context', sa.String(), nullable=True),
    sa.Column('execution_context', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.add_column('agent_preset', sa.Column('process_world', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_preset', 'process_world')
    op.drop_table('agent')
    # ### end Alembic commands ###
