"""add file upload table

Revision ID: e9f2c8d1b7a3
Revises: 0f40002d3d1f
Create Date: 2025-08-25 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f2c8d1b7a3'
down_revision: Union[str, None] = '0f40002d3d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_uploads',
        sa.Column('file_id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('original_filename', sa.String(), nullable=False),
        sa.Column('file_data', sa.LargeBinary(), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('mime_type', sa.String(), nullable=False),
        sa.Column('file_hash', sa.String(), nullable=False),
        sa.Column('upload_date', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('extracted_text', sa.Text(), nullable=True),
        sa.Column('is_processed', sa.Boolean(), nullable=True),
        sa.Column('processing_error', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['geist_user.user_id'], ),
        sa.PrimaryKeyConstraint('file_id')
    )
    
    # Create indexes for performance
    op.create_index('idx_file_uploads_user_id', 'file_uploads', ['user_id'])
    op.create_index('idx_file_uploads_upload_date', 'file_uploads', ['upload_date'])
    op.create_index('idx_file_uploads_filename', 'file_uploads', ['filename'])
    op.create_index('idx_file_uploads_hash', 'file_uploads', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_file_uploads_hash', 'file_uploads')
    op.drop_index('idx_file_uploads_filename', 'file_uploads')
    op.drop_index('idx_file_uploads_upload_date', 'file_uploads')
    op.drop_index('idx_file_uploads_user_id', 'file_uploads')
    op.drop_table('file_uploads')
    # ### end Alembic commands ###