"""add_user_settings_table

Revision ID: f1a2b3c4d5e6
Revises: e9f2c8d1b7a3
Create Date: 2025-09-28 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = 'e9f2c8d1b7a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_settings_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_agent_type', sa.String(), nullable=True),
    sa.Column('default_local_model', sa.String(), nullable=True),
    sa.Column('default_online_model', sa.String(), nullable=True),
    sa.Column('default_online_provider', sa.String(), nullable=True),
    sa.Column('default_file_archives', sa.JSON(), nullable=True),
    sa.Column('enable_rag_by_default', sa.Boolean(), nullable=True),
    sa.Column('default_max_tokens', sa.Integer(), nullable=True),
    sa.Column('default_temperature', sa.Float(), nullable=True),
    sa.Column('default_top_p', sa.Float(), nullable=True),
    sa.Column('default_frequency_penalty', sa.Float(), nullable=True),
    sa.Column('default_presence_penalty', sa.Float(), nullable=True),
    sa.Column('backup_providers', sa.JSON(), nullable=True),
    sa.Column('ui_preferences', sa.JSON(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['geist_user.user_id'], ),
    sa.PrimaryKeyConstraint('user_settings_id')
    )
    
    # Create indexes for performance
    op.create_index('idx_user_settings_user_id', 'user_settings', ['user_id'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_settings_user_id', table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
