// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/inference.proto

package inferencepb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Message represents a single message in a conversation.
type Message struct {
	Role    string `json:"role,omitempty"`
	Content string `json:"content,omitempty"`
	Name    string `json:"name,omitempty"`
}

// GenerationConfig contains parameters that control text generation.
type GenerationConfig struct {
	MaxTokens         int32    `json:"max_tokens,omitempty"`
	Temperature       float32  `json:"temperature,omitempty"`
	TopP              float32  `json:"top_p,omitempty"`
	FrequencyPenalty  float32  `json:"frequency_penalty,omitempty"`
	PresencePenalty   float32  `json:"presence_penalty,omitempty"`
	StopSequences     []string `json:"stop_sequences,omitempty"`
	TopK              int32    `json:"top_k,omitempty"`
	RepetitionPenalty float32  `json:"repetition_penalty,omitempty"`
}

// CompletionRequest contains all parameters needed for text completion.
type CompletionRequest struct {
	ModelId      string            `json:"model_id,omitempty"`
	SystemPrompt string            `json:"system_prompt,omitempty"`
	UserPrompt   string            `json:"user_prompt,omitempty"`
	Config       *GenerationConfig `json:"config,omitempty"`
	ChatHistory  []*Message        `json:"chat_history,omitempty"`
}

// UsageStats contains token usage statistics for a completion.
type UsageStats struct {
	PromptTokens     int32 `json:"prompt_tokens,omitempty"`
	CompletionTokens int32 `json:"completion_tokens,omitempty"`
	TotalTokens      int32 `json:"total_tokens,omitempty"`
}

// CompletionResponse contains the result of a completion request.
type CompletionResponse struct {
	Id           string      `json:"id,omitempty"`
	Content      string      `json:"content,omitempty"`
	FinishReason string      `json:"finish_reason,omitempty"`
	Usage        *UsageStats `json:"usage,omitempty"`
	ModelId      string      `json:"model_id,omitempty"`
	Created      int64       `json:"created,omitempty"`
}

// TokenChunk represents a single token in a streaming response.
type TokenChunk struct {
	Token        string  `json:"token,omitempty"`
	IsFinal      bool    `json:"is_final,omitempty"`
	FinishReason string  `json:"finish_reason,omitempty"`
	Index        int32   `json:"index,omitempty"`
	Logprob      float32 `json:"logprob,omitempty"`
}

// LoadModelRequest contains parameters for loading a model.
type LoadModelRequest struct {
	ModelId      string            `json:"model_id,omitempty"`
	RunnerType   string            `json:"runner_type,omitempty"`
	DeviceConfig map[string]string `json:"device_config,omitempty"`
	Quantization string            `json:"quantization,omitempty"`
}

// LoadModelResponse contains the result of loading a model.
type LoadModelResponse struct {
	Success          bool   `json:"success,omitempty"`
	Message          string `json:"message,omitempty"`
	LoadTimeMs       int64  `json:"load_time_ms,omitempty"`
	MemoryUsageBytes int64  `json:"memory_usage_bytes,omitempty"`
}

// UnloadModelRequest contains parameters for unloading a model.
type UnloadModelRequest struct {
	ModelId string `json:"model_id,omitempty"`
}

// UnloadModelResponse contains the result of unloading a model.
type UnloadModelResponse struct {
	Success bool   `json:"success,omitempty"`
	Message string `json:"message,omitempty"`
}

// ListModelsRequest contains parameters for listing models.
type ListModelsRequest struct {
	IncludeUnloaded bool `json:"include_unloaded,omitempty"`
}

// ModelInfo contains information about a model.
type ModelInfo struct {
	Id                string `json:"id,omitempty"`
	Name              string `json:"name,omitempty"`
	Loaded            bool   `json:"loaded,omitempty"`
	ContextWindow     int32  `json:"context_window,omitempty"`
	SupportsStreaming bool   `json:"supports_streaming,omitempty"`
	Family            string `json:"family,omitempty"`
	ParameterCount    int64  `json:"parameter_count,omitempty"`
	Quantization      string `json:"quantization,omitempty"`
}

// ListModelsResponse contains the list of available models.
type ListModelsResponse struct {
	Models []*ModelInfo `json:"models,omitempty"`
}

// GetModelInfoRequest contains parameters for getting model information.
type GetModelInfoRequest struct {
	ModelId string `json:"model_id,omitempty"`
}

// GetModelInfoResponse contains detailed information about a model.
type GetModelInfoResponse struct {
	Model  *ModelInfo `json:"model,omitempty"`
	Exists bool       `json:"exists,omitempty"`
}

// HealthRequest is an empty request for health checks.
type HealthRequest struct{}

// HealthResponse contains the health status of the inference service.
type HealthResponse struct {
	Status           string `json:"status,omitempty"`
	Version          string `json:"version,omitempty"`
	LoadedModels     int32  `json:"loaded_models,omitempty"`
	UptimeSeconds    int64  `json:"uptime_seconds,omitempty"`
	MemoryUsageBytes int64  `json:"memory_usage_bytes,omitempty"`
}

// InferenceServiceClient is the client API for InferenceService service.
type InferenceServiceClient interface {
	Complete(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error)
	StreamComplete(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (InferenceService_StreamCompleteClient, error)
	LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error)
	UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	GetModelInfo(ctx context.Context, in *GetModelInfoRequest, opts ...grpc.CallOption) (*GetModelInfoResponse, error)
}

type inferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceServiceClient(cc grpc.ClientConnInterface) InferenceServiceClient {
	return &inferenceServiceClient{cc}
}

func (c *inferenceServiceClient) Complete(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error) {
	out := new(CompletionResponse)
	err := c.cc.Invoke(ctx, "/geist.inference.v1.InferenceService/Complete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) StreamComplete(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (InferenceService_StreamCompleteClient, error) {
	stream, err := c.cc.NewStream(ctx, &InferenceService_ServiceDesc.Streams[0], "/geist.inference.v1.InferenceService/StreamComplete", opts...)
	if err != nil {
		return nil, err
	}
	x := &inferenceServiceStreamCompleteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InferenceService_StreamCompleteClient interface {
	Recv() (*TokenChunk, error)
	grpc.ClientStream
}

type inferenceServiceStreamCompleteClient struct {
	grpc.ClientStream
}

func (x *inferenceServiceStreamCompleteClient) Recv() (*TokenChunk, error) {
	m := new(TokenChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *inferenceServiceClient) LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error) {
	out := new(LoadModelResponse)
	err := c.cc.Invoke(ctx, "/geist.inference.v1.InferenceService/LoadModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error) {
	out := new(UnloadModelResponse)
	err := c.cc.Invoke(ctx, "/geist.inference.v1.InferenceService/UnloadModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, "/geist.inference.v1.InferenceService/ListModels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/geist.inference.v1.InferenceService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) GetModelInfo(ctx context.Context, in *GetModelInfoRequest, opts ...grpc.CallOption) (*GetModelInfoResponse, error) {
	out := new(GetModelInfoResponse)
	err := c.cc.Invoke(ctx, "/geist.inference.v1.InferenceService/GetModelInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceServiceServer is the server API for InferenceService service.
type InferenceServiceServer interface {
	Complete(context.Context, *CompletionRequest) (*CompletionResponse, error)
	StreamComplete(*CompletionRequest, InferenceService_StreamCompleteServer) error
	LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error)
	UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	GetModelInfo(context.Context, *GetModelInfoRequest) (*GetModelInfoResponse, error)
}

// UnimplementedInferenceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInferenceServiceServer struct{}

func (UnimplementedInferenceServiceServer) Complete(context.Context, *CompletionRequest) (*CompletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedInferenceServiceServer) StreamComplete(*CompletionRequest, InferenceService_StreamCompleteServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamComplete not implemented")
}
func (UnimplementedInferenceServiceServer) LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadModel not implemented")
}
func (UnimplementedInferenceServiceServer) UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnloadModel not implemented")
}
func (UnimplementedInferenceServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedInferenceServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedInferenceServiceServer) GetModelInfo(context.Context, *GetModelInfoRequest) (*GetModelInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelInfo not implemented")
}

// UnsafeInferenceServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeInferenceServiceServer interface {
	mustEmbedUnimplementedInferenceServiceServer()
}

type InferenceService_StreamCompleteServer interface {
	Send(*TokenChunk) error
	grpc.ServerStream
}

type inferenceServiceStreamCompleteServer struct {
	grpc.ServerStream
}

func (x *inferenceServiceStreamCompleteServer) Send(m *TokenChunk) error {
	return x.ServerStream.SendMsg(m)
}

func RegisterInferenceServiceServer(s grpc.ServiceRegistrar, srv InferenceServiceServer) {
	s.RegisterService(&InferenceService_ServiceDesc, srv)
}

func _InferenceService_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geist.inference.v1.InferenceService/Complete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).Complete(ctx, req.(*CompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_StreamComplete_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InferenceServiceServer).StreamComplete(m, &inferenceServiceStreamCompleteServer{stream})
}

func _InferenceService_LoadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).LoadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geist.inference.v1.InferenceService/LoadModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).LoadModel(ctx, req.(*LoadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_UnloadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).UnloadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geist.inference.v1.InferenceService/UnloadModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).UnloadModel(ctx, req.(*UnloadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geist.inference.v1.InferenceService/ListModels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geist.inference.v1.InferenceService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_GetModelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).GetModelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geist.inference.v1.InferenceService/GetModelInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).GetModelInfo(ctx, req.(*GetModelInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceService_ServiceDesc is the grpc.ServiceDesc for InferenceService service.
var InferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geist.inference.v1.InferenceService",
	HandlerType: (*InferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Complete",
			Handler:    _InferenceService_Complete_Handler,
		},
		{
			MethodName: "LoadModel",
			Handler:    _InferenceService_LoadModel_Handler,
		},
		{
			MethodName: "UnloadModel",
			Handler:    _InferenceService_UnloadModel_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _InferenceService_ListModels_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _InferenceService_Health_Handler,
		},
		{
			MethodName: "GetModelInfo",
			Handler:    _InferenceService_GetModelInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamComplete",
			Handler:       _InferenceService_StreamComplete_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/inference.proto",
}
